# -*- mode: ruby -*-
# vi: set ft=ruby :
# Example Docker edited by Jessica Rankins 6/14/2017


  # All Vagrant configuration is done below. The "2" in Vagrant.configure
  # is the configuration version.
Vagrant.configure("2") do |config|
  
  config.vm.synced_folder "./public-html/", "/var/www/html"
	  
  config.vm.provider "docker" do |d|
    # Can specify an image or a Dockerfile: 
    d.build_dir = "/vagrant/Docker/"
    d.build_args = [ "-t", "myimage" ]
    d.create_args = [ "-i", "-t" ]
    d.has_ssh = false
    d.ports = [ "8080:80" ]
    d.name = "myapachecontainer"
  end
end
